# Generated by Django 3.2.18 on 2023-04-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImgs',
        ),
    ]
