# Generated by Django 3.2.18 on 2023-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0003_sliderimgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('LinkedinURL', models.CharField(blank=True, max_length=200)),
                ('sliderImg', models.ImageField(upload_to='members_imgs/')),
            ],
        ),
    ]
