# Generated by Django 3.2.18 on 2023-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0005_rename_sliderimg_memberinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='group',
            field=models.CharField(choices=[('Global', 'Global'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green')], default=1, max_length=10),
        ),
    ]
