# Generated by Django 3.2.18 on 2023-05-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buttonText', models.CharField(blank=True, max_length=50, verbose_name='Download Button Text')),
                ('button_text_color', models.CharField(blank=True, max_length=200, verbose_name='Button Text Color')),
                ('button_color', models.CharField(blank=True, max_length=200, verbose_name='Button Color')),
                ('addfile', models.FileField(blank=True, max_length=300, upload_to='files/', verbose_name='Upload File')),
            ],
        ),
        migrations.CreateModel(
            name='FooterIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerIcon', models.CharField(help_text='Visit https://fontawesome.com/ (Use free fontawesome classnames: e.g. fa-brands fa-linkedin)', max_length=50, verbose_name='Social Media Icon')),
                ('IconUrl', models.CharField(max_length=200, verbose_name='Social Medial Url')),
                ('IconColor', models.CharField(max_length=200, verbose_name='Icon Color')),
                ('hoverColor', models.CharField(max_length=20, verbose_name='Icon Color on hover')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('group_color', models.CharField(blank=True, max_length=200, verbose_name='Group Color (linear gradient)')),
                ('group_text_color', models.CharField(blank=True, max_length=200, verbose_name='Group Text Color')),
                ('front_card_color', models.CharField(blank=True, max_length=200, verbose_name='Front Card Color (linear gradient)')),
                ('front_card_text_color', models.CharField(blank=True, max_length=200, verbose_name='Front Card Text Color')),
                ('back_card_color', models.CharField(blank=True, max_length=200, verbose_name='Back Card Color (linear gradient)')),
                ('back_card_text_color', models.CharField(blank=True, max_length=200, verbose_name='Back Card Text Color: (Hex Code)')),
            ],
        ),
        migrations.CreateModel(
            name='LogoBackgroundImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_footer_color', models.CharField(blank=True, max_length=200, verbose_name='Header & Footer Color (linear gradient)')),
                ('swiper_text', models.CharField(blank=True, max_length=200, verbose_name='Swiper Text')),
                ('swiper_color', models.CharField(blank=True, max_length=200, verbose_name='Swiper Color (linear gradient) ')),
                ('swiper_text_color', models.CharField(blank=True, max_length=200, verbose_name='Swiper Text Color ')),
                ('logo', models.ImageField(blank=True, upload_to='background_imgs/', verbose_name='Logo')),
                ('personalImg', models.ImageField(blank=True, upload_to='background_imgs/', verbose_name='Personal Image')),
                ('blobColor', models.CharField(blank=True, max_length=100, verbose_name='Blob Color: (linear gradient)')),
                ('backgroundImg', models.ImageField(blank=True, upload_to='background_imgs/', verbose_name='BackgroundImg (Optional)')),
                ('contactImg', models.ImageField(blank=True, upload_to='background_imgs/', verbose_name='ContactImg  (Optional)')),
                ('contact_heading', models.CharField(blank=True, max_length=100, verbose_name='Contact Form Heading')),
                ('contact_label_color', models.CharField(blank=True, max_length=200, verbose_name='Contact Form Labels Color')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_color', models.CharField(blank=True, max_length=200, verbose_name='Text Color')),
                ('info', models.TextField(help_text='Accpets HTML tags and inline styling', verbose_name='Personal Info')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=1000, verbose_name='URL (optional)')),
                ('image', models.ImageField(upload_to='project_imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='SwiperStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiperImgs', models.ImageField(upload_to='swiper_imgs/', verbose_name='Add a Swiper Img')),
            ],
        ),
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_card', models.TextField(help_text='Accpets HTML tags and inline styling', verbose_name='Front Card Info')),
                ('back_card', models.TextField(blank=True, help_text='Accpets HTML tags and inline styling', verbose_name='Back Card Info')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.groups')),
            ],
        ),
    ]
