# Generated by Django 3.2.18 on 2023-05-13 07:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator()])),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='social_imgs/', verbose_name='SocialMedia Icon (32x32)')),
                ('iconUrl', models.CharField(max_length=500, verbose_name='Icon URL')),
            ],
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textTop', models.CharField(max_length=300, verbose_name='TextTop')),
                ('textBottom', models.CharField(blank=True, max_length=300, verbose_name='TextBottom (Optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='team_imgs/', verbose_name='Group Picture (255x255)')),
            ],
        ),
        migrations.CreateModel(
            name='HomeColumn2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('text', models.TextField()),
                ('picture', models.ImageField(upload_to='project_imgs/', verbose_name='ProjectImg (537x269)')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImg', models.ImageField(upload_to='slider_imgs/', verbose_name='SliderImg (1100x500)')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('LinkedinURL', models.CharField(blank=True, max_length=200, verbose_name='LinkedinURL (Oprional)')),
                ('picture', models.ImageField(upload_to='members_imgs/', verbose_name='Member Picture (310x323)')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.groups')),
            ],
        ),
    ]
